# Generated by Django 3.1.5 on 2021-01-23 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('mean', models.DecimalField(decimal_places=3, max_digits=4)),
                ('variance', models.DecimalField(decimal_places=3, max_digits=4)),
            ],
        ),
    ]
