# Generated by Django 3.1.5 on 2021-01-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_squashed_0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='dsdt',
            field=models.DecimalField(decimal_places=3, default=0.1, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fund',
            name='dsdtC',
            field=models.DecimalField(decimal_places=3, default=0.1, max_digits=4),
            preserve_default=False,
        ),
    ]
