# Generated by Django 3.1.5 on 2021-01-24 10:17

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('accounts', '0001_initial'), ('accounts', '0002_auto_20210123_1841'), ('accounts', '0003_userdata_checkpoints'), ('accounts', '0004_auto_20210123_2306'), ('accounts', '0005_auto_20210123_2307')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('charity_preference', accounts.models.IntegerRangeField(default=5)),
                ('fund_preference', models.JSONField(default={'email': 'to1@example.com'})),
                ('salary', models.PositiveIntegerField(default=30)),
                ('salary_preference', accounts.models.IntegerRangeField(default=10)),
                ('checkpoints', models.JSONField(default={'Test': 1})),
                ('current_investment', models.JSONField(default=accounts.models.current_investment_default)),
            ],
            options={
                'ordering': ['user'],
                'verbose_name_plural': 'User data',
            },
        ),
    ]
