# Generated by Django 3.1.5 on 2021-01-23 18:41

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='happy',
        ),
        migrations.AddField(
            model_name='userdata',
            name='charity_preference',
            field=accounts.models.IntegerRangeField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='fund_preference',
            field=models.JSONField(default={'email': 'to1@example.com'}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='salary',
            field=models.PositiveIntegerField(default=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='salary_preference',
            field=accounts.models.IntegerRangeField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
