# Generated by Django 3.1.5 on 2021-01-24 11:37

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_squashed_0005_auto_20210123_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='age',
            field=models.PositiveIntegerField(default=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='job',
            field=models.CharField(default='Tech', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdata',
            name='charity_preference',
            field=accounts.models.IntegerRangeField(),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='checkpoints',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='fund_preference',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='salary',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='salary_preference',
            field=accounts.models.IntegerRangeField(),
        ),
    ]
