# Generated by Django 3.1.5 on 2021-01-23 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210123_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='checkpoints',
            field=models.JSONField(default={'Test': 1}),
            preserve_default=False,
        ),
    ]
