# Generated by Django 3.1.5 on 2021-01-23 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userdata_checkpoints'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdata',
            options={'ordering': ['user'], 'verbose_name_plural': 'User data'},
        ),
        migrations.AddField(
            model_name='userdata',
            name='current_investment',
            field=models.JSONField(default={'Test': 1}),
        ),
    ]
